### PR TITLE
bm_pickle: Rename is_module_accelerated to is_accelerated_module

### PR DESCRIPTION
**Pull request by corona10**
closes: https://github.com/python/pyperformance/issues/96

### CODE REVIEW

**Review by gvanrossum — APPROVED** [review]
Thanks for the quick turnaround! I hope you have write permission in this repo (AFAIK I don't).

**Comment by vstinner** [comment]
English is hard, thanks for the fix @corona10 ;-)

**Comment by gvanrossum** [comment]
I'm sorry, I have a follow-up. The help text for the `--pure-python` flag is backwards (it says "Use the C version of pickle" but it has the opposite effect). I'm beginning to think that at some point in the past the flag's sense was the opposite, and with Python 3 it was renamed, but the help text was not fixed. :-)

Finally, it looks like recent commits are duplicated, with one commit that does the work followed by a commit that touches no files by @pablogsal. What's up with that? I didn't even know you could do an empty commit. :-)

**Comment by pablogsal** [comment]
> to always squash-merge

Good point. That has to be configured by @vstinner as I don't have admin to this repo.

**Comment by gvanrossum** [comment]
Maybe the repo needs more than one owner? Redundancy! (Not that I'm
volunteering. :-)

**Comment by vstinner** [comment]
I changed @methane permission to Admin and I invited @pablogsal to give him admin permission as well.

I don't know how to change that.

**Comment by pablogsal** [comment]
> I don't know how to change that.

I changed it

**Pull request merged**
