### PR TITLE
Add an example for compile_all_revisions

### LINKED ISSUE #94: [Docs] Example for compile_all_revisions in config file
Hi all,

Recently I've been trying to benchmark a commit in cpython ``master`` branch against another commit in the same branch. The docs provide an example ``doc/benchmark.conf.sample`` file and describe it as 

> [compile_all_revisions]
> list of 'sha1=' (default branch: 'master') or 'sha1=branch'

I spent a few hours digging through the ``compile.py`` code to figure out what I was doing wrong before I finally realized I misinterpreted the docs. So I'd like to submit a PR to update the docs to make it slightly less confusing.

Thanks for your time!

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
Fixes #94

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
Thanks @Fidget-Spinner !

**Comment by vstinner** [comment]
I would prefer to put the example in a comment, so the configuration sample is directly usable.

**Comment by Fidget-Spinner** [comment]
> I would prefer to put the example in a comment, so the configuration sample is directly usable.

The hash is a real one from cpython master branch, so it runs, but I get what you mean. Would you like me to make a PR to fix that?

**Comment by vstinner** [comment]
> Would you like me to make a PR to fix that?

Hum. I looked at the rendered documentation: https://pyperformance.readthedocs.io/usage.html#compile-python-to-run-benchmarks

I forgot that the "sample" configuration already contains other values like branch names. So it's ok to keep this change without putting it into a comment.

Thanks @Fidget-Spinner for this nice enhancement ;-)

**Pull request merged**
