### PR TITLE
Add a benchmark for runtime-checkable protocols

### PR DESCRIPTION
**Pull request by AlexWaygood**
We had a longstanding issue open at CPython complaining that the performance of `isinstance()` checks against runtime-checkable protocols was a serious bottleneck for their programme. The performance of these `isinstance()` checks has been significantly improved for 3.12 compared to 3.11, but there's currently no code (to my knowledge) in pyperformance that significantly exercises `isinstance()` checks against runtime-checkable protocols.

Work towards #105.

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Might be worth having more than five. I just grepped and I found a runtime_checkable Protocol in a codebase at work with twenty one methods.....

**Comment by AlexWaygood** [comment]
> Might be worth having more than five. I just grepped and I found a runtime_checkable Protocol in a codebase at work with twenty one methods.....

I did a fair amount of grepping using grep.app while writing this benchmark. The vast majority of runtime-checkable protocols in the wild appear to have 5 members or fewer. However, there are a few codebases that make _heavy_ use of runtime-checkable protocols, and they often have "monster protocols" like the one you describe, which may have truly awful performance (and will probably have worse performance in 3.12 than they did in 3.11).

So, I'm not sure what the best thing to do here is!

**Review by brandtbucher — COMMENTED** [review]
Thanks for taking the time to do this, and for the helpful comment! I have a couple of questions/suggestions:

**Comment by AlexWaygood** [comment]
> Thanks for taking the time to do this, and for the helpful comment! I have a couple of questions/suggestions:

Thanks for the review! I think I addressed all the comments.

**Review by brandtbucher — APPROVED** [review]

**Pull request merged**
